`timescale 1ns/1ps
`default_nettype none

module aec_soc_top #(
  parameter int AXI_ADDR_WIDTH = 64,
  parameter int AXI_DATA_WIDTH = 512,
  parameter int NUM_WARPS = 4,
  parameter int NUM_BLOCKS = 1
) (
  input  wire                       ap_clk,
  input  wire                       ap_rst_n,

  input  wire [AXI_ADDR_WIDTH-1:0]  s_axi_control_awaddr,
  input  wire                       s_axi_control_awvalid,
  output wire                            s_axi_control_awready,
  input  wire [31:0]                s_axi_control_wdata,
  input  wire [3:0]                 s_axi_control_wstrb,
  input  wire                       s_axi_control_wvalid,
  output wire                            s_axi_control_wready,
  output wire [1:0]                      s_axi_control_bresp,
  output wire                            s_axi_control_bvalid,
  input  wire                       s_axi_control_bready,
  input  wire [AXI_ADDR_WIDTH-1:0]  s_axi_control_araddr,
  input  wire                       s_axi_control_arvalid,
  output wire                            s_axi_control_arready,
  output wire [31:0]                     s_axi_control_rdata,
  output wire [1:0]                      s_axi_control_rresp,
  output wire                            s_axi_control_rvalid,
  input  wire                       s_axi_control_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem0_awaddr,
  output wire [7:0]                      m_axi_gmem0_awlen,
  output wire [2:0]                      m_axi_gmem0_awsize,
  output wire [1:0]                      m_axi_gmem0_awburst,
  output wire                            m_axi_gmem0_awvalid,
  input  wire                       m_axi_gmem0_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem0_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem0_wstrb,
  output wire                            m_axi_gmem0_wlast,
  output wire                            m_axi_gmem0_wvalid,
  input  wire                       m_axi_gmem0_wready,
  input  wire [1:0]                 m_axi_gmem0_bresp,
  input  wire                       m_axi_gmem0_bvalid,
  output wire                            m_axi_gmem0_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem0_araddr,
  output wire [7:0]                      m_axi_gmem0_arlen,
  output wire [2:0]                      m_axi_gmem0_arsize,
  output wire [1:0]                      m_axi_gmem0_arburst,
  output wire                            m_axi_gmem0_arvalid,
  input  wire                       m_axi_gmem0_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem0_rdata,
  input  wire [1:0]                 m_axi_gmem0_rresp,
  input  wire                       m_axi_gmem0_rlast,
  input  wire                       m_axi_gmem0_rvalid,
  output wire                            m_axi_gmem0_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem1_awaddr,
  output wire [7:0]                      m_axi_gmem1_awlen,
  output wire [2:0]                      m_axi_gmem1_awsize,
  output wire [1:0]                      m_axi_gmem1_awburst,
  output wire                            m_axi_gmem1_awvalid,
  input  wire                       m_axi_gmem1_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem1_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem1_wstrb,
  output wire                            m_axi_gmem1_wlast,
  output wire                            m_axi_gmem1_wvalid,
  input  wire                       m_axi_gmem1_wready,
  input  wire [1:0]                 m_axi_gmem1_bresp,
  input  wire                       m_axi_gmem1_bvalid,
  output wire                            m_axi_gmem1_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem1_araddr,
  output wire [7:0]                      m_axi_gmem1_arlen,
  output wire [2:0]                      m_axi_gmem1_arsize,
  output wire [1:0]                      m_axi_gmem1_arburst,
  output wire                            m_axi_gmem1_arvalid,
  input  wire                       m_axi_gmem1_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem1_rdata,
  input  wire [1:0]                 m_axi_gmem1_rresp,
  input  wire                       m_axi_gmem1_rlast,
  input  wire                       m_axi_gmem1_rvalid,
  output wire                            m_axi_gmem1_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem2_awaddr,
  output wire [7:0]                      m_axi_gmem2_awlen,
  output wire [2:0]                      m_axi_gmem2_awsize,
  output wire [1:0]                      m_axi_gmem2_awburst,
  output wire                            m_axi_gmem2_awvalid,
  input  wire                       m_axi_gmem2_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem2_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem2_wstrb,
  output wire                            m_axi_gmem2_wlast,
  output wire                            m_axi_gmem2_wvalid,
  input  wire                       m_axi_gmem2_wready,
  input  wire [1:0]                 m_axi_gmem2_bresp,
  input  wire                       m_axi_gmem2_bvalid,
  output wire                            m_axi_gmem2_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem2_araddr,
  output wire [7:0]                      m_axi_gmem2_arlen,
  output wire [2:0]                      m_axi_gmem2_arsize,
  output wire [1:0]                      m_axi_gmem2_arburst,
  output wire                            m_axi_gmem2_arvalid,
  input  wire                       m_axi_gmem2_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem2_rdata,
  input  wire [1:0]                 m_axi_gmem2_rresp,
  input  wire                       m_axi_gmem2_rlast,
  input  wire                       m_axi_gmem2_rvalid,
  output wire                            m_axi_gmem2_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem3_awaddr,
  output wire [7:0]                      m_axi_gmem3_awlen,
  output wire [2:0]                      m_axi_gmem3_awsize,
  output wire [1:0]                      m_axi_gmem3_awburst,
  output wire                            m_axi_gmem3_awvalid,
  input  wire                       m_axi_gmem3_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem3_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem3_wstrb,
  output wire                            m_axi_gmem3_wlast,
  output wire                            m_axi_gmem3_wvalid,
  input  wire                       m_axi_gmem3_wready,
  input  wire [1:0]                 m_axi_gmem3_bresp,
  input  wire                       m_axi_gmem3_bvalid,
  output wire                            m_axi_gmem3_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem3_araddr,
  output wire [7:0]                      m_axi_gmem3_arlen,
  output wire [2:0]                      m_axi_gmem3_arsize,
  output wire [1:0]                      m_axi_gmem3_arburst,
  output wire                            m_axi_gmem3_arvalid,
  input  wire                       m_axi_gmem3_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem3_rdata,
  input  wire [1:0]                 m_axi_gmem3_rresp,
  input  wire                       m_axi_gmem3_rlast,
  input  wire                       m_axi_gmem3_rvalid,
  output wire                            m_axi_gmem3_rready,

  output wire                            interrupt
);

  localparam int AXI_STRB_WIDTH = AXI_DATA_WIDTH / 8;

  logic [AXI_ADDR_WIDTH-1:0] cu_awaddr;
  logic [7:0]                cu_awlen;
  logic [2:0]                cu_awsize;
  logic [1:0]                cu_awburst;
  logic                      cu_awvalid;
  logic                      cu_awready;
  logic [AXI_DATA_WIDTH-1:0] cu_wdata;
  logic [AXI_STRB_WIDTH-1:0] cu_wstrb;
  logic                      cu_wlast;
  logic                      cu_wvalid;
  logic                      cu_wready;
  logic [1:0]                cu_bresp;
  logic                      cu_bvalid;
  logic                      cu_bready;
  logic [AXI_ADDR_WIDTH-1:0] cu_araddr;
  logic [7:0]                cu_arlen;
  logic [2:0]                cu_arsize;
  logic [1:0]                cu_arburst;
  logic                      cu_arvalid;
  logic                      cu_arready;
  logic [AXI_DATA_WIDTH-1:0] cu_rdata;
  logic [1:0]                cu_rresp;
  logic                      cu_rlast;
  logic                      cu_rvalid;
  logic                      cu_rready;

  logic instr_ready_unused;
  logic issue_valid_unused;
  logic [1:0] issue_beat_unused;
  logic [7:0] physical_active_mask_unused;
  logic [15:0] decoded_opcode_unused;
  logic [7:0] decoded_dst_unused;
  logic [7:0] decoded_src1_unused;
  logic [7:0] decoded_src2_unused;
  logic [7:0] decoded_src3_unused;

  cu_top #(
    .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
    .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
    .NUM_WARPS(NUM_WARPS),
    .NUM_BLOCKS(NUM_BLOCKS),
    .USE_EXTERNAL_INSTR(1'b0),
    .TRACE_HALT_FINISH(1'b0)
  ) u_cu_top (
    .clk_i(ap_clk),
    .rst_ni(ap_rst_n),
    .s_axil_awaddr(s_axi_control_awaddr),
    .s_axil_awvalid(s_axi_control_awvalid),
    .s_axil_awready(s_axi_control_awready),
    .s_axil_wdata(s_axi_control_wdata),
    .s_axil_wstrb(s_axi_control_wstrb),
    .s_axil_wvalid(s_axi_control_wvalid),
    .s_axil_wready(s_axi_control_wready),
    .s_axil_bresp(s_axi_control_bresp),
    .s_axil_bvalid(s_axi_control_bvalid),
    .s_axil_bready(s_axi_control_bready),
    .s_axil_araddr(s_axi_control_araddr),
    .s_axil_arvalid(s_axi_control_arvalid),
    .s_axil_arready(s_axi_control_arready),
    .s_axil_rdata(s_axi_control_rdata),
    .s_axil_rresp(s_axi_control_rresp),
    .s_axil_rvalid(s_axi_control_rvalid),
    .s_axil_rready(s_axi_control_rready),
    .m_axi_awaddr(cu_awaddr),
    .m_axi_awlen(cu_awlen),
    .m_axi_awsize(cu_awsize),
    .m_axi_awburst(cu_awburst),
    .m_axi_awvalid(cu_awvalid),
    .m_axi_awready(cu_awready),
    .m_axi_wdata(cu_wdata),
    .m_axi_wstrb(cu_wstrb),
    .m_axi_wlast(cu_wlast),
    .m_axi_wvalid(cu_wvalid),
    .m_axi_wready(cu_wready),
    .m_axi_bresp(cu_bresp),
    .m_axi_bvalid(cu_bvalid),
    .m_axi_bready(cu_bready),
    .m_axi_araddr(cu_araddr),
    .m_axi_arlen(cu_arlen),
    .m_axi_arsize(cu_arsize),
    .m_axi_arburst(cu_arburst),
    .m_axi_arvalid(cu_arvalid),
    .m_axi_arready(cu_arready),
    .m_axi_rdata(cu_rdata),
    .m_axi_rresp(cu_rresp),
    .m_axi_rlast(cu_rlast),
    .m_axi_rvalid(cu_rvalid),
    .m_axi_rready(cu_rready),
    .instr_valid_i(1'b0),
    .instr_ready_o(instr_ready_unused),
    .instr_i(128'd0),
    .warp_active_mask_i(32'h0000_00ff),
    .issue_valid_o(issue_valid_unused),
    .issue_ready_i(1'b1),
    .issue_beat_o(issue_beat_unused),
    .physical_active_mask_o(physical_active_mask_unused),
    .decoded_opcode_o(decoded_opcode_unused),
    .decoded_dst_reg_o(decoded_dst_unused),
    .decoded_src1_reg_o(decoded_src1_unused),
    .decoded_src2_reg_o(decoded_src2_unused),
    .decoded_src3_reg_o(decoded_src3_unused)
  );

  aec_axi_hbm_4way_router #(
    .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
    .AXI_DATA_WIDTH(AXI_DATA_WIDTH)
  ) u_hbm_router (
    .clk_i(ap_clk),
    .rst_ni(ap_rst_n),
    .s_awaddr_i(cu_awaddr),
    .s_awlen_i(cu_awlen),
    .s_awsize_i(cu_awsize),
    .s_awburst_i(cu_awburst),
    .s_awvalid_i(cu_awvalid),
    .s_awready_o(cu_awready),
    .s_wdata_i(cu_wdata),
    .s_wstrb_i(cu_wstrb),
    .s_wlast_i(cu_wlast),
    .s_wvalid_i(cu_wvalid),
    .s_wready_o(cu_wready),
    .s_bresp_o(cu_bresp),
    .s_bvalid_o(cu_bvalid),
    .s_bready_i(cu_bready),
    .s_araddr_i(cu_araddr),
    .s_arlen_i(cu_arlen),
    .s_arsize_i(cu_arsize),
    .s_arburst_i(cu_arburst),
    .s_arvalid_i(cu_arvalid),
    .s_arready_o(cu_arready),
    .s_rdata_o(cu_rdata),
    .s_rresp_o(cu_rresp),
    .s_rlast_o(cu_rlast),
    .s_rvalid_o(cu_rvalid),
    .s_rready_i(cu_rready),
    .m0_awaddr_o(m_axi_gmem0_awaddr),
    .m0_awlen_o(m_axi_gmem0_awlen),
    .m0_awsize_o(m_axi_gmem0_awsize),
    .m0_awburst_o(m_axi_gmem0_awburst),
    .m0_awvalid_o(m_axi_gmem0_awvalid),
    .m0_awready_i(m_axi_gmem0_awready),
    .m0_wdata_o(m_axi_gmem0_wdata),
    .m0_wstrb_o(m_axi_gmem0_wstrb),
    .m0_wlast_o(m_axi_gmem0_wlast),
    .m0_wvalid_o(m_axi_gmem0_wvalid),
    .m0_wready_i(m_axi_gmem0_wready),
    .m0_bresp_i(m_axi_gmem0_bresp),
    .m0_bvalid_i(m_axi_gmem0_bvalid),
    .m0_bready_o(m_axi_gmem0_bready),
    .m0_araddr_o(m_axi_gmem0_araddr),
    .m0_arlen_o(m_axi_gmem0_arlen),
    .m0_arsize_o(m_axi_gmem0_arsize),
    .m0_arburst_o(m_axi_gmem0_arburst),
    .m0_arvalid_o(m_axi_gmem0_arvalid),
    .m0_arready_i(m_axi_gmem0_arready),
    .m0_rdata_i(m_axi_gmem0_rdata),
    .m0_rresp_i(m_axi_gmem0_rresp),
    .m0_rlast_i(m_axi_gmem0_rlast),
    .m0_rvalid_i(m_axi_gmem0_rvalid),
    .m0_rready_o(m_axi_gmem0_rready),
    .m1_awaddr_o(m_axi_gmem1_awaddr),
    .m1_awlen_o(m_axi_gmem1_awlen),
    .m1_awsize_o(m_axi_gmem1_awsize),
    .m1_awburst_o(m_axi_gmem1_awburst),
    .m1_awvalid_o(m_axi_gmem1_awvalid),
    .m1_awready_i(m_axi_gmem1_awready),
    .m1_wdata_o(m_axi_gmem1_wdata),
    .m1_wstrb_o(m_axi_gmem1_wstrb),
    .m1_wlast_o(m_axi_gmem1_wlast),
    .m1_wvalid_o(m_axi_gmem1_wvalid),
    .m1_wready_i(m_axi_gmem1_wready),
    .m1_bresp_i(m_axi_gmem1_bresp),
    .m1_bvalid_i(m_axi_gmem1_bvalid),
    .m1_bready_o(m_axi_gmem1_bready),
    .m1_araddr_o(m_axi_gmem1_araddr),
    .m1_arlen_o(m_axi_gmem1_arlen),
    .m1_arsize_o(m_axi_gmem1_arsize),
    .m1_arburst_o(m_axi_gmem1_arburst),
    .m1_arvalid_o(m_axi_gmem1_arvalid),
    .m1_arready_i(m_axi_gmem1_arready),
    .m1_rdata_i(m_axi_gmem1_rdata),
    .m1_rresp_i(m_axi_gmem1_rresp),
    .m1_rlast_i(m_axi_gmem1_rlast),
    .m1_rvalid_i(m_axi_gmem1_rvalid),
    .m1_rready_o(m_axi_gmem1_rready),
    .m2_awaddr_o(m_axi_gmem2_awaddr),
    .m2_awlen_o(m_axi_gmem2_awlen),
    .m2_awsize_o(m_axi_gmem2_awsize),
    .m2_awburst_o(m_axi_gmem2_awburst),
    .m2_awvalid_o(m_axi_gmem2_awvalid),
    .m2_awready_i(m_axi_gmem2_awready),
    .m2_wdata_o(m_axi_gmem2_wdata),
    .m2_wstrb_o(m_axi_gmem2_wstrb),
    .m2_wlast_o(m_axi_gmem2_wlast),
    .m2_wvalid_o(m_axi_gmem2_wvalid),
    .m2_wready_i(m_axi_gmem2_wready),
    .m2_bresp_i(m_axi_gmem2_bresp),
    .m2_bvalid_i(m_axi_gmem2_bvalid),
    .m2_bready_o(m_axi_gmem2_bready),
    .m2_araddr_o(m_axi_gmem2_araddr),
    .m2_arlen_o(m_axi_gmem2_arlen),
    .m2_arsize_o(m_axi_gmem2_arsize),
    .m2_arburst_o(m_axi_gmem2_arburst),
    .m2_arvalid_o(m_axi_gmem2_arvalid),
    .m2_arready_i(m_axi_gmem2_arready),
    .m2_rdata_i(m_axi_gmem2_rdata),
    .m2_rresp_i(m_axi_gmem2_rresp),
    .m2_rlast_i(m_axi_gmem2_rlast),
    .m2_rvalid_i(m_axi_gmem2_rvalid),
    .m2_rready_o(m_axi_gmem2_rready),
    .m3_awaddr_o(m_axi_gmem3_awaddr),
    .m3_awlen_o(m_axi_gmem3_awlen),
    .m3_awsize_o(m_axi_gmem3_awsize),
    .m3_awburst_o(m_axi_gmem3_awburst),
    .m3_awvalid_o(m_axi_gmem3_awvalid),
    .m3_awready_i(m_axi_gmem3_awready),
    .m3_wdata_o(m_axi_gmem3_wdata),
    .m3_wstrb_o(m_axi_gmem3_wstrb),
    .m3_wlast_o(m_axi_gmem3_wlast),
    .m3_wvalid_o(m_axi_gmem3_wvalid),
    .m3_wready_i(m_axi_gmem3_wready),
    .m3_bresp_i(m_axi_gmem3_bresp),
    .m3_bvalid_i(m_axi_gmem3_bvalid),
    .m3_bready_o(m_axi_gmem3_bready),
    .m3_araddr_o(m_axi_gmem3_araddr),
    .m3_arlen_o(m_axi_gmem3_arlen),
    .m3_arsize_o(m_axi_gmem3_arsize),
    .m3_arburst_o(m_axi_gmem3_arburst),
    .m3_arvalid_o(m_axi_gmem3_arvalid),
    .m3_arready_i(m_axi_gmem3_arready),
    .m3_rdata_i(m_axi_gmem3_rdata),
    .m3_rresp_i(m_axi_gmem3_rresp),
    .m3_rlast_i(m_axi_gmem3_rlast),
    .m3_rvalid_i(m_axi_gmem3_rvalid),
    .m3_rready_o(m_axi_gmem3_rready)
  );

  assign interrupt = 1'b0;

  logic unused_debug;
  assign unused_debug = ^{instr_ready_unused, issue_valid_unused, issue_beat_unused,
      physical_active_mask_unused, decoded_opcode_unused, decoded_dst_unused,
      decoded_src1_unused, decoded_src2_unused, decoded_src3_unused};
endmodule

`default_nettype wire
