#!/usr/bin/env python3
"""Command-file runtime for RTL/XSim bring-up.

This module models the fixed AEC runtime surface at a lightweight level and
emits host commands consumed by `rtl/tb_system.sv`. It performs orchestration
only: kernel math is executed by RTL simulation, not by Python.
"""

import array
import os
import struct
import subprocess
from pathlib import Path
from typing import Iterable, List, MutableSequence, Optional, Sequence, Tuple


CSR_CTRL = 0x0000
CSR_PC = 0x0004
CSR_CAP_MAGIC = 0x0020
CSR_CAP_VERSION = 0x0024
CSR_CAP_GEOMETRY = 0x0028
CSR_CAP_FEATURES = 0x002C
IMEM_WINDOW = 0x1000
DEFAULT_PARAM_BASE = 0x4000
DEFAULT_ALLOC_BASE = 0x5000
AEC_CAP_MAGIC = 0xAEC06001
AEC_CAP_VERSION = 0x00010000
AEC_CAP_GEOMETRY = 0x04040820
AEC_CAP_REQUIRED_FEATURES = 0x000007FF


class AECRuntimeError(RuntimeError):
    pass


class AECSimulatorRuntime:
    """Small command-file runtime compatible with the Stage 7.2 RTL TB."""

    def __init__(
        self,
        cmd_path="host_cmds.txt",
        *,
        alloc_base: int = DEFAULT_ALLOC_BASE,
        xsim_cmd: Optional[Sequence[str]] = None,
        cwd=None,
    ) -> None:
        self.cmd_path = Path(cmd_path)
        self.alloc_base = alloc_base
        self.next_device_addr = alloc_base
        self.xsim_cmd = list(xsim_cmd) if xsim_cmd is not None else None
        self.cwd = Path(cwd) if cwd is not None else None
        self.dumps: List[Tuple[Path, MutableSequence[int], int]] = []
        self._ran = False
        self._lines: List[str] = [
            "# generated by runtime/aec_runtime_sim.py",
        ]

    def aecContextCreate(self) -> None:
        self.emitCapabilityCheck()

    def emitCapabilityCheck(self) -> None:
        self._emit("POLL_AXIL", CSR_CAP_MAGIC, 0xFFFFFFFF, AEC_CAP_MAGIC)
        self._emit("POLL_AXIL", CSR_CAP_VERSION, 0xFFFFFFFF, AEC_CAP_VERSION)
        self._emit("POLL_AXIL", CSR_CAP_GEOMETRY, 0xFFFFFFFF, AEC_CAP_GEOMETRY)
        self._emit("POLL_AXIL", CSR_CAP_FEATURES, AEC_CAP_REQUIRED_FEATURES, AEC_CAP_REQUIRED_FEATURES)

    def aecMalloc(self, size: int) -> int:
        if size <= 0:
            raise AECRuntimeError("aecMalloc size must be positive")
        addr = self.next_device_addr
        self.next_device_addr = self._align(addr + size, 0x100)
        return addr

    def aecMemcpyH2D(self, device_ptr: int, host_array: Iterable[int]) -> None:
        for index, word in enumerate(self._words_from_host(host_array)):
            self._emit("WRITE_AXI", device_ptr + index * 4, word)

    def aecModuleLoad(self, aecbin_path) -> int:
        data = Path(aecbin_path).read_bytes()
        if not data or len(data) % 16:
            raise AECRuntimeError(".aecbin must be non-empty and 16-byte aligned")
        for word_index, (word,) in enumerate(struct.iter_unpack("<I", data)):
            self._emit("WRITE_AXIL", IMEM_WINDOW + word_index * 4, word)
        return len(data) // 16

    def aecKernelLaunch(
        self,
        pc: int,
        param_base: int = DEFAULT_PARAM_BASE,
        params_array: Optional[Iterable[int]] = None,
    ) -> None:
        if params_array is not None:
            for index, word in enumerate(self._words_from_host(params_array)):
                self._emit("WRITE_AXI", param_base + index * 4, word)
        self._emit("WRITE_AXIL", CSR_PC, pc)
        self._emit("WRITE_AXIL", CSR_CTRL, 0x00000001)

    def aecSynchronize(self) -> None:
        self._emit("POLL_AXIL", CSR_CTRL, 0x00000002, 0x00000002)

    def aecMemcpyD2H(self, host_array: MutableSequence[int], device_ptr: int, size: int) -> None:
        if size % 4:
            raise AECRuntimeError("Stage 7.2 D2H supports whole 32-bit words only")
        dump_path = self.cmd_path.with_name(f"dump_{len(self.dumps)}.hex")
        self._emit_dump(device_ptr, size // 4, dump_path)
        self.flush()
        if self.xsim_cmd is not None and not self._ran:
            self.run_simulator()
        if self._ran:
            self._load_dump(dump_path, host_array, size // 4)
        else:
            self.dumps.append((dump_path, host_array, size // 4))

    def flush(self) -> None:
        self.cmd_path.write_text("\n".join(self._lines) + "\n", encoding="ascii")

    def run_simulator(self) -> None:
        if self.xsim_cmd is None:
            raise AECRuntimeError("xsim_cmd was not configured")
        self.flush()
        subprocess.run(self.xsim_cmd, cwd=self.cwd, check=True)
        self._ran = True
        pending = list(self.dumps)
        self.dumps.clear()
        for dump_path, host_array, words in pending:
            self._load_dump(dump_path, host_array, words)

    def load_pending_dumps(self) -> None:
        pending = list(self.dumps)
        self.dumps.clear()
        for dump_path, host_array, words in pending:
            self._load_dump(dump_path, host_array, words)

    def _emit(self, op: str, *values: int) -> None:
        self._lines.append(" ".join([op] + [f"{value & 0xFFFFFFFF:08x}" for value in values]))

    def _emit_dump(self, addr: int, words: int, filename: Path) -> None:
        self._lines.append(f"DUMP_AXI {addr & 0xFFFFFFFF:08x} {words:08x} {filename.as_posix()}")

    def _words_from_host(self, host_array: Iterable[int]) -> List[int]:
        if isinstance(host_array, (bytes, bytearray, memoryview)):
            data = bytes(host_array)
            if len(data) % 4:
                raise AECRuntimeError("byte buffers must be a multiple of 4 bytes")
            return [word for (word,) in struct.iter_unpack("<I", data)]
        if isinstance(host_array, array.array):
            if host_array.itemsize != 4:
                raise AECRuntimeError("array.array inputs must use 32-bit elements")
            return [int(x) & 0xFFFFFFFF for x in host_array]
        return [int(x) & 0xFFFFFFFF for x in host_array]

    def _load_dump(self, dump_path: Path, host_array: MutableSequence[int], words: int) -> None:
        if not dump_path.exists():
            raise AECRuntimeError(f"dump file not produced: {dump_path}")
        values = [int(line.strip(), 16) for line in dump_path.read_text(encoding="ascii").splitlines() if line.strip()]
        if len(values) != words:
            raise AECRuntimeError(f"dump word count mismatch: got {len(values)}, expected {words}")
        for idx, value in enumerate(values):
            if idx < len(host_array):
                host_array[idx] = value
            else:
                host_array.append(value)

    @staticmethod
    def _align(value: int, alignment: int) -> int:
        return (value + alignment - 1) & ~(alignment - 1)
