`timescale 1ns/1ps
`default_nettype none

module aec_soc_top #(
  parameter integer AXI_ADDR_WIDTH = 64,
  parameter integer AXI_DATA_WIDTH = 512,
  parameter integer NUM_WARPS = 4,
  parameter integer NUM_BLOCKS = 1
) (

  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 ap_clk CLK" *)
  (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi_control:m_axi_gmem0:m_axi_gmem1:m_axi_gmem2:m_axi_gmem3, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 180000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0" *)
  input  wire                       ap_clk,
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 ap_rst_n RST" *)
  (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
  input  wire                       ap_rst_n,

  input  wire [AXI_ADDR_WIDTH-1:0]  s_axi_control_awaddr,
  input  wire                       s_axi_control_awvalid,
  output wire                            s_axi_control_awready,
  input  wire [31:0]                s_axi_control_wdata,
  input  wire [3:0]                 s_axi_control_wstrb,
  input  wire                       s_axi_control_wvalid,
  output wire                            s_axi_control_wready,
  output wire [1:0]                      s_axi_control_bresp,
  output wire                            s_axi_control_bvalid,
  input  wire                       s_axi_control_bready,
  input  wire [AXI_ADDR_WIDTH-1:0]  s_axi_control_araddr,
  input  wire                       s_axi_control_arvalid,
  output wire                            s_axi_control_arready,
  output wire [31:0]                     s_axi_control_rdata,
  output wire [1:0]                      s_axi_control_rresp,
  output wire                            s_axi_control_rvalid,
  input  wire                       s_axi_control_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem0_awaddr,
  output wire [7:0]                      m_axi_gmem0_awlen,
  output wire [2:0]                      m_axi_gmem0_awsize,
  output wire [1:0]                      m_axi_gmem0_awburst,
  output wire                            m_axi_gmem0_awvalid,
  input  wire                       m_axi_gmem0_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem0_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem0_wstrb,
  output wire                            m_axi_gmem0_wlast,
  output wire                            m_axi_gmem0_wvalid,
  input  wire                       m_axi_gmem0_wready,
  input  wire [1:0]                 m_axi_gmem0_bresp,
  input  wire                       m_axi_gmem0_bvalid,
  output wire                            m_axi_gmem0_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem0_araddr,
  output wire [7:0]                      m_axi_gmem0_arlen,
  output wire [2:0]                      m_axi_gmem0_arsize,
  output wire [1:0]                      m_axi_gmem0_arburst,
  output wire                            m_axi_gmem0_arvalid,
  input  wire                       m_axi_gmem0_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem0_rdata,
  input  wire [1:0]                 m_axi_gmem0_rresp,
  input  wire                       m_axi_gmem0_rlast,
  input  wire                       m_axi_gmem0_rvalid,
  output wire                            m_axi_gmem0_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem1_awaddr,
  output wire [7:0]                      m_axi_gmem1_awlen,
  output wire [2:0]                      m_axi_gmem1_awsize,
  output wire [1:0]                      m_axi_gmem1_awburst,
  output wire                            m_axi_gmem1_awvalid,
  input  wire                       m_axi_gmem1_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem1_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem1_wstrb,
  output wire                            m_axi_gmem1_wlast,
  output wire                            m_axi_gmem1_wvalid,
  input  wire                       m_axi_gmem1_wready,
  input  wire [1:0]                 m_axi_gmem1_bresp,
  input  wire                       m_axi_gmem1_bvalid,
  output wire                            m_axi_gmem1_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem1_araddr,
  output wire [7:0]                      m_axi_gmem1_arlen,
  output wire [2:0]                      m_axi_gmem1_arsize,
  output wire [1:0]                      m_axi_gmem1_arburst,
  output wire                            m_axi_gmem1_arvalid,
  input  wire                       m_axi_gmem1_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem1_rdata,
  input  wire [1:0]                 m_axi_gmem1_rresp,
  input  wire                       m_axi_gmem1_rlast,
  input  wire                       m_axi_gmem1_rvalid,
  output wire                            m_axi_gmem1_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem2_awaddr,
  output wire [7:0]                      m_axi_gmem2_awlen,
  output wire [2:0]                      m_axi_gmem2_awsize,
  output wire [1:0]                      m_axi_gmem2_awburst,
  output wire                            m_axi_gmem2_awvalid,
  input  wire                       m_axi_gmem2_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem2_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem2_wstrb,
  output wire                            m_axi_gmem2_wlast,
  output wire                            m_axi_gmem2_wvalid,
  input  wire                       m_axi_gmem2_wready,
  input  wire [1:0]                 m_axi_gmem2_bresp,
  input  wire                       m_axi_gmem2_bvalid,
  output wire                            m_axi_gmem2_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem2_araddr,
  output wire [7:0]                      m_axi_gmem2_arlen,
  output wire [2:0]                      m_axi_gmem2_arsize,
  output wire [1:0]                      m_axi_gmem2_arburst,
  output wire                            m_axi_gmem2_arvalid,
  input  wire                       m_axi_gmem2_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem2_rdata,
  input  wire [1:0]                 m_axi_gmem2_rresp,
  input  wire                       m_axi_gmem2_rlast,
  input  wire                       m_axi_gmem2_rvalid,
  output wire                            m_axi_gmem2_rready,

  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem3_awaddr,
  output wire [7:0]                      m_axi_gmem3_awlen,
  output wire [2:0]                      m_axi_gmem3_awsize,
  output wire [1:0]                      m_axi_gmem3_awburst,
  output wire                            m_axi_gmem3_awvalid,
  input  wire                       m_axi_gmem3_awready,
  output wire [AXI_DATA_WIDTH-1:0]       m_axi_gmem3_wdata,
  output wire [AXI_DATA_WIDTH/8-1:0]     m_axi_gmem3_wstrb,
  output wire                            m_axi_gmem3_wlast,
  output wire                            m_axi_gmem3_wvalid,
  input  wire                       m_axi_gmem3_wready,
  input  wire [1:0]                 m_axi_gmem3_bresp,
  input  wire                       m_axi_gmem3_bvalid,
  output wire                            m_axi_gmem3_bready,
  output wire [AXI_ADDR_WIDTH-1:0]       m_axi_gmem3_araddr,
  output wire [7:0]                      m_axi_gmem3_arlen,
  output wire [2:0]                      m_axi_gmem3_arsize,
  output wire [1:0]                      m_axi_gmem3_arburst,
  output wire                            m_axi_gmem3_arvalid,
  input  wire                       m_axi_gmem3_arready,
  input  wire [AXI_DATA_WIDTH-1:0]  m_axi_gmem3_rdata,
  input  wire [1:0]                 m_axi_gmem3_rresp,
  input  wire                       m_axi_gmem3_rlast,
  input  wire                       m_axi_gmem3_rvalid,
  output wire                            m_axi_gmem3_rready,

  output wire                            interrupt

);

  aec_soc_core #(
    .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
    .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
    .NUM_WARPS(NUM_WARPS),
    .NUM_BLOCKS(NUM_BLOCKS)
  ) u_aec_soc_core (
    .ap_clk(ap_clk),
    .ap_rst_n(ap_rst_n),
    .s_axi_control_awaddr(s_axi_control_awaddr),
    .s_axi_control_awvalid(s_axi_control_awvalid),
    .s_axi_control_awready(s_axi_control_awready),
    .s_axi_control_wdata(s_axi_control_wdata),
    .s_axi_control_wstrb(s_axi_control_wstrb),
    .s_axi_control_wvalid(s_axi_control_wvalid),
    .s_axi_control_wready(s_axi_control_wready),
    .s_axi_control_bresp(s_axi_control_bresp),
    .s_axi_control_bvalid(s_axi_control_bvalid),
    .s_axi_control_bready(s_axi_control_bready),
    .s_axi_control_araddr(s_axi_control_araddr),
    .s_axi_control_arvalid(s_axi_control_arvalid),
    .s_axi_control_arready(s_axi_control_arready),
    .s_axi_control_rdata(s_axi_control_rdata),
    .s_axi_control_rresp(s_axi_control_rresp),
    .s_axi_control_rvalid(s_axi_control_rvalid),
    .s_axi_control_rready(s_axi_control_rready),
    .m_axi_gmem0_awaddr(m_axi_gmem0_awaddr),
    .m_axi_gmem0_awlen(m_axi_gmem0_awlen),
    .m_axi_gmem0_awsize(m_axi_gmem0_awsize),
    .m_axi_gmem0_awburst(m_axi_gmem0_awburst),
    .m_axi_gmem0_awvalid(m_axi_gmem0_awvalid),
    .m_axi_gmem0_awready(m_axi_gmem0_awready),
    .m_axi_gmem0_wdata(m_axi_gmem0_wdata),
    .m_axi_gmem0_wstrb(m_axi_gmem0_wstrb),
    .m_axi_gmem0_wlast(m_axi_gmem0_wlast),
    .m_axi_gmem0_wvalid(m_axi_gmem0_wvalid),
    .m_axi_gmem0_wready(m_axi_gmem0_wready),
    .m_axi_gmem0_bresp(m_axi_gmem0_bresp),
    .m_axi_gmem0_bvalid(m_axi_gmem0_bvalid),
    .m_axi_gmem0_bready(m_axi_gmem0_bready),
    .m_axi_gmem0_araddr(m_axi_gmem0_araddr),
    .m_axi_gmem0_arlen(m_axi_gmem0_arlen),
    .m_axi_gmem0_arsize(m_axi_gmem0_arsize),
    .m_axi_gmem0_arburst(m_axi_gmem0_arburst),
    .m_axi_gmem0_arvalid(m_axi_gmem0_arvalid),
    .m_axi_gmem0_arready(m_axi_gmem0_arready),
    .m_axi_gmem0_rdata(m_axi_gmem0_rdata),
    .m_axi_gmem0_rresp(m_axi_gmem0_rresp),
    .m_axi_gmem0_rlast(m_axi_gmem0_rlast),
    .m_axi_gmem0_rvalid(m_axi_gmem0_rvalid),
    .m_axi_gmem0_rready(m_axi_gmem0_rready),
    .m_axi_gmem1_awaddr(m_axi_gmem1_awaddr),
    .m_axi_gmem1_awlen(m_axi_gmem1_awlen),
    .m_axi_gmem1_awsize(m_axi_gmem1_awsize),
    .m_axi_gmem1_awburst(m_axi_gmem1_awburst),
    .m_axi_gmem1_awvalid(m_axi_gmem1_awvalid),
    .m_axi_gmem1_awready(m_axi_gmem1_awready),
    .m_axi_gmem1_wdata(m_axi_gmem1_wdata),
    .m_axi_gmem1_wstrb(m_axi_gmem1_wstrb),
    .m_axi_gmem1_wlast(m_axi_gmem1_wlast),
    .m_axi_gmem1_wvalid(m_axi_gmem1_wvalid),
    .m_axi_gmem1_wready(m_axi_gmem1_wready),
    .m_axi_gmem1_bresp(m_axi_gmem1_bresp),
    .m_axi_gmem1_bvalid(m_axi_gmem1_bvalid),
    .m_axi_gmem1_bready(m_axi_gmem1_bready),
    .m_axi_gmem1_araddr(m_axi_gmem1_araddr),
    .m_axi_gmem1_arlen(m_axi_gmem1_arlen),
    .m_axi_gmem1_arsize(m_axi_gmem1_arsize),
    .m_axi_gmem1_arburst(m_axi_gmem1_arburst),
    .m_axi_gmem1_arvalid(m_axi_gmem1_arvalid),
    .m_axi_gmem1_arready(m_axi_gmem1_arready),
    .m_axi_gmem1_rdata(m_axi_gmem1_rdata),
    .m_axi_gmem1_rresp(m_axi_gmem1_rresp),
    .m_axi_gmem1_rlast(m_axi_gmem1_rlast),
    .m_axi_gmem1_rvalid(m_axi_gmem1_rvalid),
    .m_axi_gmem1_rready(m_axi_gmem1_rready),
    .m_axi_gmem2_awaddr(m_axi_gmem2_awaddr),
    .m_axi_gmem2_awlen(m_axi_gmem2_awlen),
    .m_axi_gmem2_awsize(m_axi_gmem2_awsize),
    .m_axi_gmem2_awburst(m_axi_gmem2_awburst),
    .m_axi_gmem2_awvalid(m_axi_gmem2_awvalid),
    .m_axi_gmem2_awready(m_axi_gmem2_awready),
    .m_axi_gmem2_wdata(m_axi_gmem2_wdata),
    .m_axi_gmem2_wstrb(m_axi_gmem2_wstrb),
    .m_axi_gmem2_wlast(m_axi_gmem2_wlast),
    .m_axi_gmem2_wvalid(m_axi_gmem2_wvalid),
    .m_axi_gmem2_wready(m_axi_gmem2_wready),
    .m_axi_gmem2_bresp(m_axi_gmem2_bresp),
    .m_axi_gmem2_bvalid(m_axi_gmem2_bvalid),
    .m_axi_gmem2_bready(m_axi_gmem2_bready),
    .m_axi_gmem2_araddr(m_axi_gmem2_araddr),
    .m_axi_gmem2_arlen(m_axi_gmem2_arlen),
    .m_axi_gmem2_arsize(m_axi_gmem2_arsize),
    .m_axi_gmem2_arburst(m_axi_gmem2_arburst),
    .m_axi_gmem2_arvalid(m_axi_gmem2_arvalid),
    .m_axi_gmem2_arready(m_axi_gmem2_arready),
    .m_axi_gmem2_rdata(m_axi_gmem2_rdata),
    .m_axi_gmem2_rresp(m_axi_gmem2_rresp),
    .m_axi_gmem2_rlast(m_axi_gmem2_rlast),
    .m_axi_gmem2_rvalid(m_axi_gmem2_rvalid),
    .m_axi_gmem2_rready(m_axi_gmem2_rready),
    .m_axi_gmem3_awaddr(m_axi_gmem3_awaddr),
    .m_axi_gmem3_awlen(m_axi_gmem3_awlen),
    .m_axi_gmem3_awsize(m_axi_gmem3_awsize),
    .m_axi_gmem3_awburst(m_axi_gmem3_awburst),
    .m_axi_gmem3_awvalid(m_axi_gmem3_awvalid),
    .m_axi_gmem3_awready(m_axi_gmem3_awready),
    .m_axi_gmem3_wdata(m_axi_gmem3_wdata),
    .m_axi_gmem3_wstrb(m_axi_gmem3_wstrb),
    .m_axi_gmem3_wlast(m_axi_gmem3_wlast),
    .m_axi_gmem3_wvalid(m_axi_gmem3_wvalid),
    .m_axi_gmem3_wready(m_axi_gmem3_wready),
    .m_axi_gmem3_bresp(m_axi_gmem3_bresp),
    .m_axi_gmem3_bvalid(m_axi_gmem3_bvalid),
    .m_axi_gmem3_bready(m_axi_gmem3_bready),
    .m_axi_gmem3_araddr(m_axi_gmem3_araddr),
    .m_axi_gmem3_arlen(m_axi_gmem3_arlen),
    .m_axi_gmem3_arsize(m_axi_gmem3_arsize),
    .m_axi_gmem3_arburst(m_axi_gmem3_arburst),
    .m_axi_gmem3_arvalid(m_axi_gmem3_arvalid),
    .m_axi_gmem3_arready(m_axi_gmem3_arready),
    .m_axi_gmem3_rdata(m_axi_gmem3_rdata),
    .m_axi_gmem3_rresp(m_axi_gmem3_rresp),
    .m_axi_gmem3_rlast(m_axi_gmem3_rlast),
    .m_axi_gmem3_rvalid(m_axi_gmem3_rvalid),
    .m_axi_gmem3_rready(m_axi_gmem3_rready),
    .interrupt(interrupt)
  );
endmodule

`default_nettype wire
