`timescale 1ns/1ps
`default_nettype none

// Three-stage, fixed-latency SFU lane.
//
// Stage 1: classify IEEE-754 inputs, normalize RCP subnormals with a
//           leading-zero detector plus barrel shift, and form the LUT index.
// Stage 2: synchronous BRAM LUT read.
// Stage 3: pack normal/special results.
//
// The arithmetic matches the LUT model generated by tests/sfu_model_sweep.py.
// In particular, the visible RCP/EXP2 error contract remains relative-error
// bounded by the golden-model sweep; this pipeline changes only timing.
module sfu_lane #(
  parameter int LUT_BITS = 12
) (
  input  wire logic        clk_i,
  input  wire logic        rst_ni,
  input  wire logic        start_i,
  input  wire logic [15:0] opcode_i,
  input  wire logic [2:0]  subop_i,
  input  wire logic [31:0] src_val_i,
  output logic             result_valid_o,
  output logic [31:0]      result_o
);
  import aec_pkg::*;

  localparam int LUT_ENTRIES = 1 << LUT_BITS;
  localparam logic [31:0] CANONICAL_NAN = 32'h7fc00000;
  localparam logic [31:0] POS_INF       = 32'h7f800000;
  localparam logic [31:0] POS_ZERO      = 32'h00000000;
  localparam logic [31:0] POS_ONE       = 32'h3f800000;

  // A synchronous read is required for RAMB inference.  The two ROMs are
  // populated by the sweep script and registered in the Vitis XO package.
  (* ram_style = "block" *) logic [22:0] rcp_lut [0:LUT_ENTRIES-1];
  (* ram_style = "block" *) logic [22:0] exp2_lut [0:LUT_ENTRIES-1];

  logic             stage1_valid_q;
  logic [2:0]       stage1_subop_q;
  logic             stage1_special_q;
  logic [31:0]      stage1_special_result_q;
  logic             stage1_sign_q;
  logic signed [9:0] stage1_out_exp_q;
  logic [LUT_BITS-1:0] stage1_lut_idx_q;

  logic             stage2_valid_q;
  logic [2:0]       stage2_subop_q;
  logic             stage2_special_q;
  logic [31:0]      stage2_special_result_q;
  logic             stage2_sign_q;
  logic signed [9:0] stage2_out_exp_q;
  logic [22:0]      stage2_lut_data_q;

  logic             calc_special;
  logic [31:0]      calc_special_result;
  logic             calc_sign;
  logic signed [9:0] calc_out_exp;
  logic [LUT_BITS-1:0] calc_lut_idx;

  initial begin
    $readmemh("sfu_rcp_lut.mem", rcp_lut);
    $readmemh("sfu_exp2_lut.mem", exp2_lut);
  end

  function automatic logic [31:0] make_inf(input logic sign);
    make_inf = {sign, 8'hff, 23'd0};
  endfunction

  function automatic logic [31:0] make_zero(input logic sign);
    make_zero = {sign, 31'd0};
  endfunction

  // Fixed, logarithmic-priority leading-zero detector.  This replaces the
  // previous 23-iteration feedback loop used to normalize RCP subnormals.
  function automatic logic [4:0] lzd24(input logic [23:0] value);
    begin
      casez (value)
        24'b1???????????????????????: lzd24 = 5'd0;
        24'b01??????????????????????: lzd24 = 5'd1;
        24'b001?????????????????????: lzd24 = 5'd2;
        24'b0001????????????????????: lzd24 = 5'd3;
        24'b00001???????????????????: lzd24 = 5'd4;
        24'b000001??????????????????: lzd24 = 5'd5;
        24'b0000001?????????????????: lzd24 = 5'd6;
        24'b00000001????????????????: lzd24 = 5'd7;
        24'b000000001???????????????: lzd24 = 5'd8;
        24'b0000000001??????????????: lzd24 = 5'd9;
        24'b00000000001?????????????: lzd24 = 5'd10;
        24'b000000000001????????????: lzd24 = 5'd11;
        24'b0000000000001???????????: lzd24 = 5'd12;
        24'b00000000000001??????????: lzd24 = 5'd13;
        24'b000000000000001?????????: lzd24 = 5'd14;
        24'b0000000000000001????????: lzd24 = 5'd15;
        24'b00000000000000001???????: lzd24 = 5'd16;
        24'b000000000000000001??????: lzd24 = 5'd17;
        24'b0000000000000000001?????: lzd24 = 5'd18;
        24'b00000000000000000001????: lzd24 = 5'd19;
        24'b000000000000000000001???: lzd24 = 5'd20;
        24'b0000000000000000000001??: lzd24 = 5'd21;
        24'b00000000000000000000001?: lzd24 = 5'd22;
        24'b000000000000000000000001: lzd24 = 5'd23;
        default:                       lzd24 = 5'd24;
      endcase
    end
  endfunction

  function automatic logic signed [31:0] f32_to_q12_trunc(input logic [31:0] x);
    logic sign;
    logic [7:0] exp_in;
    logic [22:0] frac_in;
    logic [23:0] mant;
    logic [63:0] magnitude;
    integer shift;
    begin
      sign = x[31];
      exp_in = x[30:23];
      frac_in = x[22:0];
      mant = (exp_in == 8'd0) ? {1'b0, frac_in} : {1'b1, frac_in};
      shift = integer'(exp_in) - 138;
      if (exp_in == 8'd0) begin
        f32_to_q12_trunc = 32'sd0;
      end else if (shift >= 0) begin
        magnitude = {40'd0, mant} << shift;
        f32_to_q12_trunc = sign ? -$signed(magnitude[31:0]) : $signed(magnitude[31:0]);
      end else if (shift <= -24) begin
        f32_to_q12_trunc = 32'sd0;
      end else begin
        magnitude = {40'd0, mant} >> (-shift);
        f32_to_q12_trunc = sign ? -$signed(magnitude[31:0]) : $signed(magnitude[31:0]);
      end
    end
  endfunction

  function automatic logic [31:0] pack_rcp(
    input logic sign,
    input logic signed [9:0] out_exp,
    input logic [22:0] lut_value
  );
    logic [23:0] out_sig;
    logic [22:0] subnormal_frac;
    integer subnormal_shift;
    begin
      if (out_exp >= 10'sd255) begin
        pack_rcp = make_inf(sign);
      end else if (out_exp <= 10'sd0) begin
        out_sig = {1'b1, lut_value};
        subnormal_shift = 1 - out_exp;
        if (subnormal_shift >= 24) begin
          subnormal_frac = 23'd0;
        end else begin
          subnormal_frac = out_sig >> subnormal_shift;
        end
        pack_rcp = {sign, 8'd0, subnormal_frac};
      end else begin
        pack_rcp = {sign, out_exp[7:0], lut_value};
      end
    end
  endfunction

  always_comb begin
    logic sign;
    logic [7:0] exp_in;
    logic [22:0] frac_in;
    logic [23:0] normalized_mant;
    logic [4:0] norm_shift;
    logic signed [31:0] x_q12;
    logic signed [31:0] whole;
    logic signed [10:0] exponent_tmp;

    calc_special = 1'b1;
    calc_special_result = CANONICAL_NAN;
    calc_sign = src_val_i[31];
    calc_out_exp = '0;
    calc_lut_idx = '0;
    sign = src_val_i[31];
    exp_in = src_val_i[30:23];
    frac_in = src_val_i[22:0];
    normalized_mant = {1'b1, frac_in};
    norm_shift = 5'd0;
    x_q12 = 32'sd0;
    whole = 32'sd0;
    exponent_tmp = 11'sd0;

    if (aec_opcode_e'(opcode_i) != AEC_OP_SFU) begin
      calc_special_result = 32'd0;
    end else begin
      unique case (subop_i)
        3'd0: begin // RCP.f32
          if ((exp_in == 8'hff) && (frac_in != 23'd0)) begin
            calc_special_result = CANONICAL_NAN;
          end else if ((exp_in == 8'd0) && (frac_in == 23'd0)) begin
            calc_special_result = make_inf(sign);
          end else if (exp_in == 8'hff) begin
            calc_special_result = make_zero(sign);
          end else begin
            calc_special = 1'b0;
            if (exp_in == 8'd0) begin
              norm_shift = lzd24({1'b0, frac_in});
              normalized_mant = {1'b0, frac_in} << norm_shift;
              exponent_tmp = 11'sd1 - $signed({1'b0, norm_shift});
            end else begin
              exponent_tmp = $signed({1'b0, exp_in});
            end
            calc_sign = sign;
            calc_lut_idx = normalized_mant[22 -: LUT_BITS];
            calc_out_exp = 10'sd253 - exponent_tmp;
          end
        end
        3'd1: begin // EXP2.f32
          if ((exp_in == 8'hff) && (frac_in != 23'd0)) begin
            calc_special_result = CANONICAL_NAN;
          end else if (src_val_i == 32'h7f800000) begin
            calc_special_result = POS_INF;
          end else if (src_val_i == 32'hff800000) begin
            calc_special_result = POS_ZERO;
          end else if ((exp_in == 8'd0) && (frac_in == 23'd0)) begin
            calc_special_result = POS_ONE;
          end else if (!sign && (src_val_i >= 32'h43000000)) begin
            calc_special_result = POS_INF;
          end else if (sign && ({1'b0, src_val_i[30:0]} > 32'h42fc0000)) begin
            calc_special_result = POS_ZERO;
          end else begin
            calc_special = 1'b0;
            x_q12 = f32_to_q12_trunc(src_val_i);
            whole = x_q12 >>> LUT_BITS;
            calc_lut_idx = x_q12[LUT_BITS-1:0];
            calc_out_exp = whole + 32'sd127;
          end
        end
        default: begin
          calc_special_result = CANONICAL_NAN;
        end
      endcase
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      stage1_valid_q <= 1'b0;
      stage1_subop_q <= 3'd0;
      stage1_special_q <= 1'b0;
      stage1_special_result_q <= 32'd0;
      stage1_sign_q <= 1'b0;
      stage1_out_exp_q <= '0;
      stage1_lut_idx_q <= '0;
      stage2_valid_q <= 1'b0;
      stage2_subop_q <= 3'd0;
      stage2_special_q <= 1'b0;
      stage2_special_result_q <= 32'd0;
      stage2_sign_q <= 1'b0;
      stage2_out_exp_q <= '0;
      stage2_lut_data_q <= '0;
      result_valid_o <= 1'b0;
      result_o <= 32'd0;
    end else begin
      // Stage 1: classification, subnormal LZD, normalization, and index.
      stage1_valid_q <= start_i;
      if (start_i) begin
        stage1_subop_q <= subop_i;
        stage1_special_q <= calc_special;
        stage1_special_result_q <= calc_special_result;
        stage1_sign_q <= calc_sign;
        stage1_out_exp_q <= calc_out_exp;
        stage1_lut_idx_q <= calc_lut_idx;
      end

      // Stage 2: inferred synchronous BRAM read.
      stage2_valid_q <= stage1_valid_q;
      if (stage1_valid_q) begin
        stage2_subop_q <= stage1_subop_q;
        stage2_special_q <= stage1_special_q;
        stage2_special_result_q <= stage1_special_result_q;
        stage2_sign_q <= stage1_sign_q;
        stage2_out_exp_q <= stage1_out_exp_q;
        if (stage1_subop_q == 3'd0) begin
          stage2_lut_data_q <= rcp_lut[stage1_lut_idx_q];
        end else begin
          stage2_lut_data_q <= exp2_lut[stage1_lut_idx_q];
        end
      end

      // Stage 3: special-case selection and IEEE-754 result packing.
      result_valid_o <= stage2_valid_q;
      if (stage2_valid_q) begin
        if (stage2_special_q) begin
          result_o <= stage2_special_result_q;
        end else if (stage2_subop_q == 3'd0) begin
          result_o <= pack_rcp(stage2_sign_q, stage2_out_exp_q, stage2_lut_data_q);
        end else begin
          if (stage2_out_exp_q >= 10'sd255) begin
            result_o <= POS_INF;
          end else if (stage2_out_exp_q <= 10'sd0) begin
            result_o <= POS_ZERO;
          end else begin
            result_o <= {1'b0, stage2_out_exp_q[7:0], stage2_lut_data_q};
          end
        end
      end
    end
  end
endmodule

`default_nettype wire
